(display (cons (list 1 2) (list 3 4)))(newline)
(display (list (list 1 2) (list 3 4)))(newline)
(display (list (list 1 2) 3 4))(newline)
(display (cons (list 1 2) (cons 3 (cons 4 '()))))(newline)
(newline)(newline)
(display (list 1 (list 2 (list 3 4))))(newline)
(display (list 1 2 3 4))(newline)