(define (make-account password balance)
  ; SHORTCUT: I should reset this whenever the password is valid
  (define invalid-attempts 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
                balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (invalid-pass . args)
    (set! invalid-attempts (+ invalid-attempts 1))
    (if (> invalid-attempts 2)
        "Calling police!"
        "Incorrect password"))
  (define (dispatch p m)
    (cond ((not (eq? p password)) invalid-pass)
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request " m))))
  dispatch)

(let ((account (make-account 'my-pass 100)))
  (display ((account 'my-pass 'withdraw) 50))(newline)
  (display ((account 'fake-pass 'withdraw) 25))(newline)
  (display ((account 'fake-pass 'withdraw) 25))(newline)
  (display ((account 'fake-pass 'withdraw) 25))(newline)
  (display ((account 'my-pass 'withdraw) 50))(newline))